# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-03-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='başlık')),
                ('content', models.TextField(verbose_name='içerik')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
